name = "plug-digital-import"
account_id = "4a7b555c733231ff62dc4a25c9a18209"
compatibility_date = "2025-09-01"
main = "scripts/import-products.worker.ts"

[[d1_databases]]
binding = "DB"
database_name = "plug-digital-db"
database_id = "03952470-a406-4b93-b3e5-4f98b2df9817"
